import React from "react";

const Footer = () => {
	return (
		<div>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
			<li>footer</li>
		</div>
	);
};

export default Footer;
